name: Build Module
on:
  workflow_dispatch:
defaults:
  run:
    shell: pwsh

jobs:
  builds-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@main"
      - name: Build the library
        run: |
          build.ps1
