name: Build Module

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@main"
      - name: Build the library
        run: |
          build.ps1
  