name: Build PSConf2023
on:
  push:
    branches:
      # - main
      - ProudRabbit
    paths-ignore:
      - CHANGELOG.md
      # - .github/**
    # tags:
    #   - '**'
    #   - '!*preview*'

defaults:
  run:
    shell: pwsh

env:
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  defaultBranch: main

jobs:
  Build_Stage_Package_Module:
    name: Package Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Evaluate Next Version
        uses: gittools/actions/gitversion/setup@v0
        with:
          configFilePath: GitVersion.yml
      - name: Builde & Package Module
        env:
          ModuleVersion: ${{ env.gitVersion.NuGetVersionV2 }}
        run: |
          ./build.ps1 -ResolveDependency -Tasks pack -Verbose
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}
