name: Test Build Module
on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  defaultBranch: main
  Agent.Source.Git.ShallowFetchDepth: 0

jobs:
  Build_Stage_Package_Module:
    name: Package Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Package
        run: |
          ./build.ps1 -ResolveDependency -Tasks pack
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: |
            ${{ env.buildFolderName }}

  Test_Stage_test_linux:
    name: Linux
    runs-on: ubuntu-latest
    needs:
      - Build_Stage_Package_Module
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}
      - name: Run Tests
        run: |
          ./build.ps1 -Tasks test
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: (${{ job.status }} != 'cancelled')
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/NUnit*.xml
          name: Linux
      - name: Publish Test Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/
          name: CodeCoverageLinux

  Test_Stage_test_windows_core:
    name: Windows (PWSH)
    runs-on: windows-latest
    needs:
      - Build_Stage_Package_Module
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}
      - name: Run Tests
        run: |
          ./build.ps1 -Tasks test
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: (${{ job.status }} != 'cancelled')
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/NUnit*.xml
          name: Windows (PWSH)
      - name: Publish Test Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/
          name: CodeCoverageWinPWSH

  Test_Stage_test_windows_ps:
    name: Windows (Windows PowerShell)
    runs-on: windows-latest
    needs:
      - Build_Stage_Package_Module
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}
      - name: Run Tests
        shell: powershell
        run: |
          .\build.ps1 -Tasks test
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: (${{ job.status }} != 'cancelled')
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/NUnit*.xml
          name: Windows (Windows PowerShell)
      - name: Publish Test Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/
          name: CodeCoverageWinPS51

  Test_Stage_test_macos:
    name: MacOS
    runs-on: macos-latest
    needs:
      - Build_Stage_Package_Module
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}
      - name: Run Tests
        run: |
          ./build.ps1 -Tasks test
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: (${{ job.status }} != 'cancelled')
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/NUnit*.xml
          name: MacOS
      - name: Publish Test Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/
          name: CodeCoverageMacOS
