name: Build Module
on: [push]
defaults:
  run:
    shell: pwsh
jobs:
  builds-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the library
        run: |
          build.ps1
