name: Do something on merge into main

# Trigger when a pull request into main branch is closed, which can happen either on merge or manual close...
on:
  push:
    branches:
      - ProudRabbit

  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main

defaults:
  run:
    shell: pwsh

jobs:
  thejob:
    # if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    steps:
      - name: "Run"
        run: |
          $headers = @{}
          $headers.Add("AccessToken", "token ${{ secrets.GITHUB_TOKEN }}")

          $params = @{}
          $params.Add("Uri", "https://api.github.com/repos/Proud-Rabbit/PSRToolbox/releases")
          $params.Add("Method", "GET")
          $params.Add("Headers", $headers)
          $params.Add("UseDefaultCredentials", $true)
          $params.Add("UseBasicParsing", $true)
          $params.Add("TimeoutSec", 0)

          [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
          $result = Invoke-WebRequest @params
          Write-Host $result.Content
